#
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

list_repo:
  - name: tap-deploy
    category: script

  - name: space-shuttle-demo
    category: space-shuttle-demo

  - name: auth-gateway
    category: auth-gateway

  - name: data-acquisition
    category: maven

  - name: data-catalog
    category: data-catalog

  - name: dataset-publisher
    category: maven

  - name: downloader
    category: maven

  - name: h2o-model-provider
    category: maven

  - name: h2o-provisioner
    category: maven

  - name: h2o-scoring-engine-publisher
    category: maven

  - name: metadata-parser
    category: maven

  - name: model-catalog
    category: maven

  - name: platform-snapshot
    category: maven

  - name: tap-cli
    category: go_exe

  - name: tap-api-service
    category: pack_sh
    copy_files:
      - src: "{{ repos_checkout_dir }}/tap-cli/application/*"
        dest: "{{ repos_checkout_dir }}/tap-api-service/resources/"

  - name: tap-blob-store
    category: tap-blob-store
    produces:
      - name: tap-blob-store
      - name: tap-blob-store/minio

  - name: tap-ca
    category: pack_sh

  - name: tap-catalog
    category: pack_sh

  - name: console
    category: console

  - name: tap-container-broker
    category: pack_sh

  - name: tap-image-factory
    category: pack_sh

  - name: tap-metrics
    category: tap-metrics
    produces:
      - name: metrics-grafana
      - name: metrics-ceph-exporter
      - name: metrics-grafana-uaa-syncer

  - name: uaa
    category: gradle

  - name: tap-monitor
    category: pack_sh

  - name: tap-nginx-dyn-stream
    category: pack_sh

  - name: tap-nginx-ingress
    category: pack_sh

  - name: tap-template-repository
    category: pack_sh

  - name: gateway
    category: pack_sh

  - name: scoring-pipelines
    category: dockerfile

  - name: gearpump-dashboard
    category: gearpump-dashboard

  - name: scoring-engine
    category: scoring-engine

  - name: uploader
    category: maven

  - name: user-management
    category: maven

  - name: workflow-scheduler
    category: maven

  - name: gearpump-broker
    category: maven

  - name: h2o-broker
    category: maven

  - name: hdfs-broker
    category: maven

  - name: hive-broker
    category: maven

  - name: zookeeper-broker
    category: maven

  - name: jupyter
    category: dockerfile

  - name: key-counter
    category: maven

  - name: micro-reverse-proxy
    category: pack_sh

  - name: platform-tests
    category: pack_sh

  - name: tap-ceph-broker
    category: rpm

# List of categories that will be build using tap-component module
component_build_categories:
  - maven
  - pack_sh
  - rpm
  - gradle
  - go_exe
  - tap-metrics
  - data-catalog
  - auth-gateway
  - tap-blob-store
  - console
  - gearpump-dashboard
  - scoring-engine
  - space-shuttle-demo

# List of categories for which a Docker image will be build
image_build_categories:
  - pack_sh
  - gradle
  - data-catalog
  - dockerfile
  - console

# List of categories that do not produce a Docker image
imageless_categories:
  - go_exe
  - script
  - rpm
  - space-shuttle-demo

# List of categories that produce output directory with application files
sample_apps_categories:
  - space-shuttle-demo

organization: "intel-data"
repos_checkout_dir: "{{ ansible_env.HOME }}/tap-repositories"

registry_host: "localhost"
registry_distribution_port: 5001

build_environment:
  GOROOT: "/opt/go"
  PATH: "{{ ansible_env.PATH }}:/opt/maven/bin:/opt/go/bin:{{ ansible_env.HOME }}/bin:/usr/local/bin:/usr/bin:/{{ ansible_env.HOME }}/.gem/ruby/bin"
  M2_HOME: /opt/maven

rpms_directory: "{{ ansible_env.HOME }}/tap-rpms"
sample_apps_directory: "{{ ansible_env.HOME }}/sample_apps"
