#
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Create rpmbuild into home user directory
  file:
    path: "{{ ansible_env.HOME }}/rpmbuild/{{ item }}"
    owner: "{{ TARGET_REGULAR_USER }}"
    state: directory
  with_items:
    - BUILD
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS

- name: Create .rpmmacros file under user home directory
  file:
    path: "{{ ansible_env.HOME }}/.rpmmacros"
    owner: "{{ TARGET_REGULAR_USER }}"
    state: touch
  changed_when: False

- name: Add config into .rpmmacros file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.rpmmacros"
    line: '%_topdir %(echo $HOME)/rpmbuild'
    state: present

