---
yum_repos:
  cloudera-manager:
    name: Cloudera Manager
    baseurl: http://archive.cloudera.com/cm5/redhat/7/x86_64/cm/5.7.1/
    gpgkey: http://archive.cloudera.com/cm5/redhat/7/x86_64/cm/RPM-GPG-KEY-cloudera
    gpgcheck: 1
  mysql56-community:
    name: MySQL 5.6 Community Server
    baseurl: http://repo.mysql.com/yum/mysql-5.6-community/el/7/$basearch/
    enabled: 1
    gpgcheck: 0
  nginx:
    name: nginx
    description: nginx-official
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: no
  docker:
    name: docker
    description: docker project repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    gpgkey: https://yum.dockerproject.org/gpg
    ip_resolve: 4
    repo_gpgcheck: yes
    retries: 10
    state: present
  ceph:
    name: ceph
    description: ceph repository
    baseurl: http://download.ceph.com/rpm-jewel/el7/x86_64/
    gpgkey: https://download.ceph.com/keys/release.asc
    gpgcheck: 1
  kubernetes:
    name: kubernetes
    description: kubernetes repo
    baseurl: https://s3.amazonaws.com/trustedanalytics/v0.8.0/rpm/
    gpgcheck: 0
  zabbix:
    name: zabbix
    baseurl: http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/
    enabled: 1
    gpgcheck: 0
  zabbix-nonsup:
    name: zabbix non supported
    baseurl: http://repo.zabbix.com/non-supported/rhel/7/x86_64/
    enabled: 1
    gpgcheck: 0

yum_remote_dependencies:
  - { url: "http://download.oracle.com/otn-pub/java/jdk/8u72-b15/jdk-8u72-linux-x64.rpm", name: "jdk1.8.0_72.rpm", header: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" }

yum_dependencies:
  - cloudera-manager-daemons
  - cloudera-manager-server 
  - cloudera-manager-agent 
  - cloudera-manager-server-db-2 
  - krb5-workstation 
  - python2 
  - libselinux-python 
  - python-httplib2.noarch 
  - unzip 
  - ntp 
  - bind-license 
  - bind-libs-lite
  - python-pip 
  - expect 
  - MySQL-python 
  - mysql-community-server 
  - mysql-connector-java
  - lvm2
  - krb5-server
  - krb5-pkinit
  - openssl
  - openssl-devel
  - yum-utils
  - nginx
  - etcd
  - docker-engine
  - iptables-services
  - flannel-0.6.1-1.el7.centos.x86_64
  - kubernetes-1.3.7-1.el7.centos.x86_64
  - kubernetes-apiserver-1.3.7-1.el7.centos.x86_64
  - kubernetes-client-1.3.7-1.el7.centos.x86_64
  - kubernetes-controller-manager-1.3.7-1.el7.centos.x86_64
  - kubernetes-kubelet-1.3.7-1.el7.centos.x86_64
  - kubernetes-master-1.3.7-1.el7.centos.x86_64
  - kubernetes-node-1.3.7-1.el7.centos.x86_64
  - kubernetes-proxy-1.3.7-1.el7.centos.x86_64
  - kubernetes-scheduler-1.3.7-1.el7.centos.x86_64
  - at
  - audit
  - autogen-libopts
  - avahi-libs
  - bash-completion
  - bc
  - bind-utils
  - boost-iostreams
  - boost-program-options
  - boost-random
  - boost-regex
  - boost-system
  - boost-thread
  - bzip2
  - ceph-base
  - ceph-common
  - ceph-fuse
  - ceph-mon
  - ceph-osd
  - ceph-radosgw
  - ceph-selinux
  - cryptsetup
  - cups-client
  - cups-libs
  - ed
  - fcgi
  - fuse-libs
  - gdisk
  - git
  - gperftools-libs
  - gpm-libs
  - hdparm
  - htop
  - iftop
  - iotop
  - iputils
  - jq
  - leveldb
  - libaio
  - libbabeltrace
  - libcephfs1
  - libgnome-keyring
  - libicu
  - librados2
  - libradosstriper1
  - librbd1
  - librgw2
  - libtomcrypt
  - libtommath
  - libunwind
  - lsof
  - lttng-ust
  - m4
  - mailcap
  - mailx
  - nethogs
  - nmap-ncat
  - patch
  - php-fpm
  - postgresql-server
  - psmisc
  - python2-crypto
  - python2-ecdsa
  - python2-paramiko
  - python-psycopg2
  - python-babel
  - python-cephfs
  - python-flask
  - python-httplib2
  - python-itsdangerous
  - python-jinja2
  - python-keyczar
  - python-markupsafe
  - python-netaddr
  - python-pyasn1
  - python-rados
  - python-rbd
  - python-werkzeug
  - redhat-lsb-core
  - redhat-lsb-submod-security
  - redis
  - rsync
  - screen
  - smartmontools
  - socat
  - spax
  - sshpass
  - strace
  - sysstat
  - tcpdump
  - telnet
  - time
  - tmux
  - userspace-rcu
  - vim
  - zabbix-agent
  - zabbix-server-pgsql
  - zabbix-web-pgsql

