# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---

- name: Prepare yum definitions
  set_fact:
    pdir: "{{ offline_workdir }}/out/yum"
    ydir: "{{ offline_workdir }}/out/yum/repository"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ pdir }}"
    - "{{ ydir }}"

- name: Download yum dependencies
  shell: yum install -y --releasever=7 --installroot="/tmp" --downloadonly --downloaddir "{{ ydir }}" {{ yum_dependencies | join(' ') }}

- name: Make yum cache
  shell: yum --assumeyes makecache

- name: Create transaction file (for reverse dependencies)
  shell: yum install --assumeno --releasever=7 {{ yum_dependencies | join(' ') }}
  register: yum_result
  failed_when: "{{ 'yum load-transaction' not in yum_result.stdout }}"

- name: Get transaction file path
  set_fact:
    transaction_file: "{{ yum_result.stdout_lines | select('match', '.*yum load-transaction.*') | list | first | regex_replace('.*yum load-transaction ([^\\s]*).*', '\\1') }}"

- name: Download yum reverse dependencies
  shell: yum load-transaction --downloaddir "{{ ydir }}" --downloadonly {{ transaction_file }}

- name: Download all remote dependencies
  get_url:
    dest: "{{ ydir }}/{{ item.name }}"
    headers: "{{ item.header }}"
    url: "{{ item.url }}"
    force: true
  with_list: "{{ yum_remote_dependencies }}"

- name: Also download all dependencies for remote dependencies
  shell: yum install -y --releasever=7 --installroot="/tmp" --downloadonly --downloaddir "{{ ydir }}" "{{ ydir }}/{{ item.name }}"
  with_items: "{{ yum_remote_dependencies }}"

- name: Create yum repo
  shell: createrepo "{{ pdir }}"

